### ISSUE TITLE
python 2.7 Travis tests

### ISSUE THREAD

**Issue by mkelley** [mommermi/sbpy#29]
Shouldn't we drop the Python 2.7 tests in Travis?

**Comment by mommermi** [comment]
We should. I guess that means that we build `sbpy` only for Python 3.x?

**Comment by mkelley** [comment]
If we start by requiring `astropy` 3.0, then we test python 3.5+ https://github.com/astropy/astropy-APEs/blob/master/APE10.rst

**Comment by mommermi** [comment]
Sounds reasonable to me. Just to be safe, I check our proposal and we wrote '*SBPy will use Python 3;'*. Any objections to requiring `astropy` >=3.0 and hence Python >=3.5?

**Comment by mkelley** [comment]
Well, if astropy doesn't support <3.5, we will be on the hook for writing sbpy code to handle whatever problems might arise.

**Comment by mommermi** [comment]
True... let's not even think about this.

**Comment by mkelley** [comment]
Looks like f0347a30 addresses this issue.
